# Generated by Django 2.1.7 on 2019-03-12 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190312_1010'),
        ('users', '0002_auto_20190312_1112'),
    ]

    operations = [
    ]
