# Generated by Django 2.1.7 on 2019-03-08 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('holes', models.IntegerField(validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(36)])),
                ('tee_type', models.CharField(max_length=8)),
            ],
        ),
    ]
