# Generated by Django 2.1.7 on 2019-03-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='play',
            field=models.BooleanField(default=False),
        ),
    ]
