# Generated by Django 2.1.7 on 2019-03-14 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_play'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course.Course')),
                ('thoughts', models.CharField(max_length=1800)),
            ],
            bases=('course.course',),
        ),
    ]
